// Channel names only, with no runtime imports, so the sandboxed preload can bundle it.
export const CALL_NAMES = [
  'getStatus',
  'listAlerts',
  'getAlertDetail',
  'decide',
  'reopen',
  'undoAction',
  'approveProposal',
  'rejectProposal',
  'listRules',
  'setRuleMode',
  'listActions',
  'listEvents',
  'eventStats',
  'getSettings',
  'setTheme',
  'sendTestAlert',
  'openMain',
  'closePopup',
  'fitPopup',
  'quit',
  'getSetup',
  'checkSetup',
  'setSetupMode',
  'skipSetupStep',
  'finishSetup',
  'restartSetup',
  'saveApiKey',
  'clearApiKey',
  'openSettingsPane',
  'installHelper',
  'uninstallHelper',
] as const;

export const PUSH_NAMES = ['changed', 'popup', 'navigate', 'theme', 'events'] as const;
